# Generated by Django 2.0 on 2018-02-09 14:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20180209_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='zdjecie',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
