# Generated by Django 2.0 on 2018-02-09 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_item_zdjecie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='price',
            new_name='cena',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='nazwa',
        ),
    ]
